server:
  port: 16100

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: q.5xo.cc:8848
      username: app_learn
      password: learn
      discovery:
        namespace: 741c3fbb-909a-48a4-a2bf-ceded9f15ff0
        group: app_learn
    gateway:
      discovery:
        locator:
          enabled: true
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: localhost:8849
