server:
  port: 16102

spring:
  application:
    name: stock-service

  cloud:
    nacos:
      server-addr: q.5xo.cc:8848
      username: app_learn
      password: learn
      discovery:
        namespace: 741c3fbb-909a-48a4-a2bf-ceded9f15ff0
        group: app_learn
